micronaut:
  application:
    name: r2dbcInheritance
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      db-type: mariadb
netty:
  default:
    allocator:
      max-order: 3
